viosey/hexo-theme-material

layout/_partial/toc_button.ejs
Hide toc button when toc is empty
=> Hide toc button when toc list is empty

_config.yml, languages/en.yml, languages/zh-CN.yml, languages/zh-TW.yml, layout/_partial/blog_info.ejs, layout/_partial/post-info-share.ejs
=> Add share to Facebook

layout/_partial/footer-left.ejs, layout/_partial/isolate-sns_list.ejs
I replaced every:
```
<% if(theme.sns.twitter == undefined){ %>
<% } else{ %>
...
<% } %>
```
by a simpler and more readable:
```
<% if(theme.sns.twitter){ %>
...
<% } %>
```
=> refactor(sns): simplify conditional display

_config.yml, layout/_partial/sidebar-navigation.ejs
I reopen https://github.com/viosey/hexo-theme-material/pull/118
=> feat(pages): allow page icons in sidebar

layout/_partial/blog_info.ejs
`<a href="<%= theme.url.logo || '#' %>">`
instead of
`<a href="<% if(theme.url.logo !=null) { %> <%= theme.url.logo %> <%} else { %> # <% } %>">`
=> refactor(url): improve logo url decision making

layout/_widget/duoshuo.ejs
`data-thread-key="<% theme.comment.duoshuo_thread_key_type === 'id' ? page.id : page.path %>"`
instead of 
`data-thread-key="<% if(theme.comment.duoshuo_thread_key_type == "id"){%><%= page.id %><% } else { %><%= page.path %><% } %>" `
=> refactor(duoshuo): improve thread key statement

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
The issue https://github.com/viosey/hexo-theme-material/issues/42 should be closed and replaced by these templates
=> Add issue and pull requests templates

layout/_partial/head.ejs
Aim to fix https://github.com/viosey/hexo-theme-material/issues/70
=> feat(keywords): add post keywords as meta keywords

_config.yml, layout/_partial/head.ejs
Please be sure to put the `canary` branch as the target for your pull request.
=> feat(analytics): Add Analytics for #75

layout/_partial/head.ejs
=> feat(opengraph): Add opengraph support for posts

.github/PULL_REQUEST_TEMPLATE.md
=> refactor(template): add more details

contributing.json
Mirror changes from gitmagic branch due to gitmagic limit.
=> refactor(gitmagic): Mirror changes

_config.template.yml, layout/_partial/sidebar-navigation.ejs
____
Add support for sidebar customize.
You can customize your sidebar icons in config file now.
(I remove the *I'm Feeling Lucky* item as well)
____
- You have to update your _config.yml in order to use this feature and avoid bug.
=> feat(sidebar): add support for customize sidebar

layout/_partial/Paradox-search.ejs
____
Migration of fix https://github.com/viosey/hexo-theme-material/issues/168 from `canary` by @theonlygusti
____
Using search input will not display an autocomplete above the search result...
=> fix(autocomplete): disable browser autocomplete

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, contributing.json, layout/_partial/Paradox-search.ejs
____
Merge mater into canary
____
=> chore(branch): merge master into canary

_config.template.yml, layout/_partial/sidebar-footer.ejs, layout/_partial/sidebar-navigation.ejs, layout/_partial/sidebar.ejs
____
- Sidebar dividers can now be displayed or removed after each sidebar item.
- Footer can be hidden.
____
Update the sidebar configuration part by changing `divider` value for the different items.
=> feat(sidebar): can hide divider and footer

_config.template.yml, layout/_partial/config_css.ejs, layout/_partial/import_pace.ejs, source/css/pace/center-atom.css
=> Update(feat/progressbar): Add setting for user's own style and bring back center-atom style

layout/layout.ejs
____
add the "lang" to < html >
```
<html lang="<%- config.language.substring(0,2) %>">
```
Closes issue #188;
____
=> feat(layout): add the "lang" to < html >

_config.template.yml, languages/ar.yml, languages/de.yml, languages/en.yml, languages/es.yml, languages/fr.yml, languages/ja.yml, languages/ms.yml, languages/zh-CN.yml, languages/zh-TW.yml, layout/_partial/comment.ejs, layout/_widget/disqus_click.ejs, source/js/ripple.js
____
- Add a way to load  Disqus comments：“Dissqus_click_to_load”. It means that Disqus will be load after your click. Useful as it is, it help improve  experience of Chinese who are trapped by the GFW so that avoid …
=> feat(comments): add "Disqus_click_to_load" to improve in-GFW-users

.gitignore, layout/_partial/Paradox-post_entry.ejs, layout/_widget/duoshuo.ejs
____
1. 使用多说评论系统时无法正确显示评论数目
2. `duoshuo.ejs` 和 `Paradox-post_entry.ejs` 中存在的语法错误
____
=> fix(comment):duoshuo comment counts display issues and some other errors

README.md
____
update README,md for contributing rules.
____
=> docs(readme): add read contributing rules.

languages/pt-BR.yml
____
Added Portuguese Brazil (pt-BR) language translation.
____
=> feat(lang): add brazil(pt-BR) translation

layout/_partial/head.ejs
____
Update Version number from 1.2.6 to 1.3.0
____
=> refactor(version): update 1.2.6 to 1.3.0

_config.template.yml, layout/_partial/head.ejs, layout/_partial/import_js.ejs, layout/_widget/nprogress.ejs, layout/_widget/page-gallery.ejs
____
Add support for using Private CDN to boost the theme
____
Please clone the code in this branch, and then run a test. 
You can use the `https://materialcdn.nfz.moe/material-theme/hexo` as the …
=> feat(materialcdn): bring materialcdn up.

languages/zh-CN.yml
=> refactor(language): zh-CN

layout/_partial/Paradox-post-thumbnail.ejs, layout/_partial/Paradox-post_entry-thumbnail.ejs, layout/_partial/Paradox-post_entry.ejs, layout/_partial/daily_pic.ejs, layout/_partial/head.ejs, layout/_partial/import_js.ejs, source/js/queue.js
____
Use lazyload on all Thumbnail image to improve page load speed.
____
=> refactor(lazyload): use lazyload on all Thumbnail

layout/_partial/head.ejs
____
- Add support for dns-prefetch
____
=> feat(head): add support for dns-prefetch

layout/_partial/import_js.ejs
____
Let the search dependencies only load on home page.
____
=> refactor(search): let the search dependencies only load on home page

_config.template.yml, layout/index.ejs
____
Fix pin on top method.
Now,if `hexo-helper-post-top` is install, pin on top will automatically turn on.
____
=> fix(top post): fix pin on top

layout/_partial/import_js.ejs
____
Remove queue load idle
____
=> fix(queue): remove load idle

layout/_partial/isolate_info.ejs
____
fix pages list won't show on info, and add support for html tag and muiltline in slogan.
____
**Verification …
=> fix(isolation): pages list won't show on info

layout/layout.ejs
____
Allow site config language is null. Improve fault tolerance. 
____
=> refactor(language): improve language fault tolerance

layout/_partial/head.ejs, layout/_partial/import_js.ejs
=> refactor(uc): add uc compatible to footer

layout/_widget/page-gallery.ejs
____
fix queue not start issue in gallery. 
fix #285 
____
=> fix(gallery): fix queue in gallery

layout/_partial/import_js.ejs
____
Add Version code & Theme information to console log.
____
=> style(console): add version code to console log

layout/_widget/mathjax.ejs
=> fix(#283): add misssed mathjax config back

_config.template.yml, layout/_partial/footer.ejs
____
Specify the date when the site was setup. For example, if you set it as 2015, then footer will show `© 2015 - …
=> feat(footer): enhancement for copyright

layout/_partial/sidebar-navigation.ejs
____
add rel="nofollow" to sidebar homepage
____
=> fix(sidebar): add nofollow to sidebar homepage

layout/_partial/config_css.ejs
____
Add materialcdn support for fonts.
____
=> feat(materialcdn): add materialcdn support for fonts

layout/_partial/isolate_info.ejs
=> fix(isolatelink): fix isolate page link

_config.template.yml, layout/_partial/head.ejs
____
Add support for `google search onsole site verification`
____
=> feat(head): add meta tag for google_site_verification

languages/ar.yml, languages/de.yml, languages/en.yml, languages/es.yml, languages/fr.yml, languages/ja.yml, languages/ms.yml, languages/pt-BR.yml, languages/zh-CN.yml, languages/zh-TW.yml, layout/post.ejs
____
Remove the useless `private` layout.
____
=> remove(layout): remove private layout

layout/_partial/head.ejs, layout/_partial/import_js.ejs
____
Add the `type="text/ls-javascript"`
Fix the background load exception for the first time loading
____ …
=> fix(Bing): Fix the background load exception for the first time loading

layout/_partial/head.ejs
=> feat(og): optimize opengraph

README.md
=> refactor(README): minor changes

_config.template.yml, layout/_partial/toc_button.ejs
____
~~Now users can configure whether the line_number of toc will show or not in `front-matter`~~
~~For …
=> feat/fix(#345): add configuration of toc_linenumber support

_config.template.yml, layout/_widget/comment/163gentie/common.ejs, layout/_widget/comment/163gentie/enter.ejs, layout/_widget/comment/163gentie/main.ejs
=> feat(comment): add 163gentie support

_config.template.yml, layout/_partial/head.ejs
____
Now we have site_verification support for baidu.
____
I run a test of it and it works.
=> feat(head): add site verification support for baidu

_config.template.yml, layout/_partial/head.ejs, layout/_partial/structured-data.ejs
____
I add structured-data support for seo.
**I thought there might be something wrong if users have not configure …
=> feat(head): add structured-data support for seo.

layout/_partial/toc_button.ejs
=> fix(toc): fix a bug of the close tag missing.

layout/_partial/head.ejs
- simplify the description
- add twitter card protocol
- fix some issue of canonical link
- some else..
____
- …
=> feat/refactor(head): minor changes.

layout/_partial/blog_info.ejs, layout/_partial/post-info-share.ejs
____
```url_for(path)``` will include the root automatically. So I delete the ```config.root``` before ```url_for(path)```.
Please refer to [https://hexo.io/docs/helpers.html](https://hexo.io/docs/helpers.html)
____
=> fix(share_menu): url issue of sharing links

languages/en.yml
=> improve translate

layout/_partial/head.ejs, layout/_partial/structured-data.ejs
=> fix(head): fix some issue of date format

_config.template.yml, layout/_widget/comment/livere/enter.ejs, layout/_widget/comment/livere/main.ejs
____
Add livere comment system support.
____
=> feat(comment): add livere comment system support.

layout/_widget/qrcode.ejs
____
Add another Qrcode API : `chart.googleapis.com`
Use the language configuration to decide which api to be use. …
=> feat(qrcode): add google qrcode api support

_config.template.yml, layout/_partial/footer.ejs
=> feat(footer): footer text customize support

layout/_partial/import_js.ejs
=> feat(footer): add custom code footer

layout/_partial/config_dnsprefetch.ejs, layout/_partial/head.ejs
____
- split the dns-prefetch
- add `chart.google.com`
- add `custom_font_host`
____
No …
=> feat(head): minor changes of dns-prefetch

_config.template.yml, layout/_partial/config_font.ejs
=> feat(fonts): import material icons as vendors

layout/_partial/config_css.ejs
=> fix(scrollbar): fix x-scroll when toTop show

layout/_widget/comment/163gentie/main.ejs
=> 修复配置参数 gentie_thread_key_type 引用错误

.travis.yml
=> chore/feat(ci): bring up travis

_config.template.yml, layout/_widget/comment/163gentie/common.ejs, layout/_widget/comment/163gentie/enter.ejs, layout/_widget/comment/163gentie/main.ejs
____
Remove the 163gentie support, as the 163gentie will stop service at 2017.08.01.
____ …
=> remove(comment): remove 163 gentie

scripts/lib/css_lsload.js
=> fix(lsload): css resources error

_config.template.yml, layout/_partial/config_font.ejs, layout/_partial/head.ejs, layout/_partial/import_js.ejs, layout/_widget/mathjax.ejs, layout/_widget/nprogress.ejs
____
Vendors > MaterialCDN > (Google Fonts > Google Fonts Proxy) > Origin
____
No …
=> fix: file load order and fallback

layout/_partial/import_js.ejs, layout/_partial/toc_button.ejs
____
Not generate toc button when toc is empty instead of hide it in realtime javascript on browser.
____
=> feat(toc): auto hide toc when generate instead of realtime js

_config.template.yml, layout/_widget/comment/gitment/common.ejs, layout/_widget/comment/gitment/enter.ejs, layout/_widget/comment/gitment/main.ejs
____
Gitment is a comment system based on GitHub Issues, which can be used in the frontend without any server-side implementation. Now I add it in this theme.
____
1. [Click here](https://github.com/settings/applications/new) to register an OAuth application, and you will get a client ID and a client secret.
Make sure the callback URL is right. Generally it's the origin of your site, like [https://shriek.tech](https://shriek.tech).
2.  Change the theme settings :
```yaml
use: gitment
gitment_repo:   # git repo of the hexo
gitment_owner:  # git repo's owner
gitment_client_id:  # github app client id …
```
=> feat(comment): add gitment

layout/_widget/comment/disqus_click/main.ejs
=> feat(comment): disqus accessible check

layout/_widget/comment/valine/common.ejs
____
Change the local path to the online path for Valine.min.js
____
=> fix(comment): change valine.min.js link

layout/_widget/comment/gitment/common.ejs, layout/_widget/comment/gitment/enter.ejs
____
fix the error that gitment common script can't find the commet dom in pages isn't with the post layout. 
____ …
=> fix(gitment): fixed a error

_config.template.yml, layout/_partial/config_font.ejs
=> feat(font): add new font.host catnet

layout/_widget/dnsprefetch.ejs
=> feat: add dns-prefetch for valine

README.md
=> chore(README): minor style changes

layout/_partial/Paradox-post-info.ejs, layout/_partial/post-content.ejs, layout/post.ejs
=> Add option 'hide_license', 'hide_share' and 'hide_post_info'.

languages/ru.yml
____
Add Russian translation.
____
=> Add Russian translation

layout/_widget/dnsprefetch.ejs
=>  feat: update dns-prefetch

_config.template.yml, layout/_widget/comment/wildfire/common.ejs, layout/_widget/comment/wildfire/enter.ejs, layout/_widget/comment/wildfire/main.ejs
=> feat(comment): add wildfire

layout/index.ejs, layout/layout.ejs
- [x ] Feature
- [x ] No
____
add arial-label for button. Improve accessible reading ability.
____
**Verification …
=> Improvement of Accessible Reading

_config.template.yml, layout/_widget/page-gallery.ejs
____
解锁"图库"页面被注释的信息面板并在设置里添加一些项目, 且使用Formspree作为邮件转发服务.
注: Formspree功能未经测试. (懒.jpg)
____
No …
=> feat(gallery): unlock gallery information panel

_config.template.yml
change words "form" to "from"
____
____
=> docs(_config.template.yml): fix two typos

languages/ko.yml
=> feat (lang) : add language - korean

layout/_widget/comment/wildfire/enter.ejs
____
Oops, adding a line makes difference.
____
=> fix(wildfire): fix padding

_config.template.yml
=> fix(busuanzi): update host
